<a href="https://colab.research.google.com/github/trottiemcqueen/tensorflow-fundamentals/blob/main/002_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Cont. Creating tensors with `tf.Variable`

In [ ]:
import tensorflow as tf

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

const tensor is common sense like normal code, is unchangeable. Note: Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as Tensorflow will do this for us. If in doubt, use `tf.constant` and change later if needed.

### Creating random tensors

Random tensors are tensore of some abitrary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf. constant([[10, 7],
                             [3, 4],
                             [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

🦾 **Exercise:** Read through Tensorflow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

In [ ]:
import tensorflow as tf


random_3 = tf.random.Generator.from_seed(256)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(256)
random_4 = random_4.normal(shape=(3, 2))
random_5 = tf.random.Generator.from_seed(500)
random_5 = random_5.normal(shape=(3, 2))
random_6 = tf.random.Generator.from_seed(500)
random_6 = random_6.normal(shape=(3, 2))
random_7 = tf.random.Generator.from_seed(900)
random_7 = random_7.normal(shape=(3, 2))
random_8 = tf.random.Generator.from_seed(900)
random_8 = random_8.normal(shape=(3, 2))

random_3, random_4, random_5, random_6, random_7, random_8


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0359411 ,  1.5315233 ],
        [ 0.51527184, -0.76588607],
        [ 1.6272374 ,  0.04138071]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0359411 ,  1.5315233 ],
        [ 0.51527184, -0.76588607],
        [ 1.6272374 ,  0.04138071]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.6467872 , -0.70762324],
        [-0.05593427, -0.52378434],
        [-0.02676746, -0.8452239 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.6467872 , -0.70762324],
        [-0.05593427, -0.52378434],
        [-0.02676746, -0.8452239 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.03976075, -0.09035786],
        [ 1.3931489 , -0.20710102],
        [-1.0587467 ,  0.66279715]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.03976075, -0.09035786],
        [ 1.3931489 , -0.20710102],
    

In [ ]:
lets_shuffle1 = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]])
tf.random.shuffle(lets_shuffle1),

random_3 = tf.constant([[-1.0359411 ,  1.5315233 ],
        [ 0.51527184, -0.76588607],
        [ 1.6272374 ,  0.04138071]])
tf.random.shuffle(random_3),

lets_shuffle2 = tf.constant([[111, 70],
                             [33, 44],
                             [2, 5]])
tf.random.shuffle(lets_shuffle2),

lets_shuffle3 = tf.constant([[10, 7],
                             [303, 411],
                             [200, 553]])
tf.random.shuffle(lets_shuffle3),

lets_shuffle4 = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]])
tf.random.shuffle(lets_shuffle4),

lets_shuffle5 = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]])
tf.random.shuffle(lets_shuffle5),

lets_shuffle6 = tf.constant([[10, 70],
                             [31, 413],
                             [23, 35]])
tf.random.shuffle(lets_shuffle6),

lets_shuffle7 = tf.constant([[10, 70],
                             [3, 40],
                             [201, 51]])
tf.random.shuffle(lets_shuffle7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10,  70],
       [  3,  40],
       [201,  51]], dtype=int32)>

Learned a lesson when implementing the shuffle, is that only recognizes and runs the last function. Will not run a list of functions like the generating random.Generator. ***Note:*** Will have to run the shuffle one tensor at a time.

### Creating tensors from NumPy arrays

Another side note to think about

In [ ]:
import tensorflow as tf

tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

In [3]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [4]:
# Create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [5]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [8]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [9]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>