<a href="https://colab.research.google.com/github/trottiemcqueen/tensorflow-fundamentals/blob/main/003_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Manipulating tensors (basic operations)

***Basic Operations***

+, -, *, /

In [1]:
import tensorflow as tf
import numpy as np

# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [2]:
# Original tensor is unchanged
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [3]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [4]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [5]:
tensor = tensor - 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [6]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

# When using *, and / there is no need to create a variable to apply basic operation

In [7]:
# We can use tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [8]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Matrix multiplication with tensors part 1

## In machine learning, matrix multiplication is one of the most common tensor operations.

In [9]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor) # matrix multiplication

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [10]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [11]:
tensor.shape

TensorShape([2, 2])

In [12]:
# Create a (3, 2) tensor
x = tf.constant([[3, 4],
                 [8, 9],
                 [5, 6]])
# Create another (3, 2) tensor
y = tf.constant([[3, 4],
                 [5, 6],
                 [7, 8]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [8, 9],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape


***Resource*** : Info and example of matrix multiplication: https://www.mathsisfun.com/algrbra/matrix-multiplying.html